### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by tiny6996** [mailcow/mailcow-ansiblerole#12]
It has Come to my attention that a lot of the mailcow apps don't have a license. Is it possible to add one?

**Comment by ntimo** [comment]
Hey,
yes indeed the role is currently not licensed. I would like to change the license to the same license mailcow is licensed under  (GNU General Public License v3.0).

Therefore I would like to ask our past contributors for their approval. Please leave a comment to this issue and state your approval.

@0boro 
@jonasc 
@domrim 
@n0emis

If everyone aggress I will add the license to the repo.

**Comment by 0boro** [comment]
I am fine with this

**Comment by n0emis** [comment]
I agree with the license change

**Comment by domrim** [comment]
I also am fine with the license.

**Comment by jonasc** [comment]
I'm fine, too; sorry for being a bit late to reply.

**Comment by ntimo** [comment]
I have now added the license to the project. Thanks everyone for your time :)

https://github.com/mailcow/mailcow-ansiblerole/commit/9bba11e3557c9c0092ff3da412b55ffd2dd08549
