### ISSUE TITLE
Wrong container name in "running" check

### ISSUE THREAD

**Issue by ckoehler** [mailcow/mailcow-ansiblerole#30]
I just tried to update mailcow and had the update task skipped. Looked like the container name was different on my system than the task check below:

https://github.com/mailcow/mailcow-ansiblerole/blob/3968ac431c80eb16ff5bc6fbcb18dd122862d4ce/tasks/main.yml#L56

My containers were called "{{ mailcow__docker_compose_project_name }}-nginx-mailcow-1" (dashes instead of underscores). Not sure if my setup was just weird, and I already fixed it for me, but maybe there's more to it and others are affected.

**Comment by felixoi** [comment]
I can confirm this.
